<a href="https://colab.research.google.com/github/KriachkoAS/simplified_quantum_pc/blob/main/transmit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
class QPC:
  def __init__(self, n):
    self.n = n
    self.states = np.zeros([2] * n)
    self.states[tuple([0] * n)] = 1

qpc = QPC(3)
qpc.states

array([[[1., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [ ]:
def func(self, indices, matrix):
  permutation = tuple(
      np.setdiff1d(np.arange(self.n), indices)
      ) + tuple(indices)
  res = self.states.transpose(permutation)\
    .reshape([2] * (self.n - len(indices)) + [-1, 1])
  res = matrix @ res
  res = res.reshape([2] * self.n)\
    .transpose(np.argsort(permutation))
  self.states = res
  return res

QPC._group_and_apply = func

def func(self, *indices):
  for index in indices:
    qs = self._group_and_apply([index], (1/2)**(1/2)*np.array([[1, 1], [1, -1]]))
  return self.states

QPC.h = func

qpc = QPC(3)
qpc.h(0, 1, 2, 0, 1)

array([[[7.07106781e-01, 7.07106781e-01],
        [2.29934717e-17, 2.29934717e-17]],

       [[2.53429949e-17, 2.53429949e-17],
        [6.15876663e-34, 6.15876663e-34]]])

In [ ]:
def func(self, *indices):
  matrix = np.diag(np.ones(2 ** len(indices), dtype = int))
  matrix[-2:, -2:] = [[0, 1], [1, 0]]
  self._group_and_apply(indices, matrix)
  return self.states

QPC.x = func

qpc = QPC(3)
qpc.x(0)
qpc.x(0, 1)
qpc.x(0, 1, 2)

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 1.]]])

In [ ]:
def func(self, *indices):
  matrix = np.diag(np.ones(2 ** len(indices), dtype = int))
  matrix[-1, -1] = -1
  self._group_and_apply(indices, matrix)
  return self.states

QPC.z = func

qpc = QPC(2)
#3rd party
qpc.h(1)
qpc.x(1, 0)
#sender (manipulates only [1] qubit)
message = [True, True]
if message[0]:
  qpc.z(1)
if message[1]:
  qpc.x(1)
#reseiver
qpc.x(1, 0)
qpc.h(1)
qpc.states.flatten()

array([ 0.00000000e+00,  0.00000000e+00,  4.26642159e-17, -1.00000000e+00])